receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  otlphttp:
    endpoint: http://host.docker.internal:8081


connectors:
  spanmetrics:
    namespace: span.metrics
    exemplars:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      exporters: [otlphttp]
