name: Integration Tests
on: pull_request
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.0"
        cache-dependency-path: "**/*.sum"
    - name: Run tests
      with:
        cache-dependency-path: "**/*.sum"
      run: |
        cd integration-tests/tests
        ./run-integration-tests.sh