name: Main CI

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  test-crds:
    uses: ./.github/workflows/test-crds.yml

  test-dashboards:
    uses: ./.github/workflows/test-dashboards.yml

  crosscompile:
    uses: ./.github/workflows/crosscompile.yml

  check-containers:
    uses: ./.github/workflows/check-containers.yml

  publish-release:
    needs: [test, test-crds, test-dashboards, crosscompile, check-containers]
    uses: ./.github/workflows/publish-release.yml
    with:
      ref: ${{ github.ref_name }}
      is_release: false
    permissions:
      contents: read
      id-token: write
